sudo: false # faster builds
language: java
jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

env:
  global:
    - CODECOV_TOKEN=109638e7-23da-4e48-9ac0-199a3db59550

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=hippalus -Dsonar.login=544625bf78707bed3be3f1f0c74cd97ae5a267dd

after_success:
  - bash <(curl -s https://codecov.io/bash)