spring:
  flyway:
    enabled: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:incidentmanagement
        username: root
        password: root123
        hikari:
          pool-name: incident.management.connection.pool
